### ISSUE TITLE
Ok to reuse?

### ISSUE THREAD

**Issue by aduis** [dropbox/dbx-career-framework#4]
Hi there, your career framework is awesome and we are happy that we have discovered it. We are about to have our own career framework. We are considering to base it on your development and customize your framework to our needs. Unfortuntely, there is no license defined in this repo and that by default means that we can't reuse it. Is that your intetion or did you simply forget to add a license?
Thanks, Andre

**Comment by jterk** [comment]
Hi! Our intention when [we published this was absolutely to encourage reuse and adaptation of the framework](https://dropbox.tech/culture/sharing-our-engineering-career-framework-with-the-world).

**Comment by jterk** [comment]
@aduis following up on your comment - the contents of this repository are now explicitly available under the Apache 2.0 license: https://github.com/dropbox/dbx-career-framework/blob/main/LICENSE
