### ISSUE TITLE
Is there a specific reason why there isn't an overview available to provide a quick differentiation between the various levels?

### ISSUE THREAD

**Issue by Alexxtheonly** [dropbox/dbx-career-framework#7]
We have implemented this framework within our company and are currently engaged in a discussion regarding the publication of our condensed internal overview.

Have you explored the option of creating a simplified overview to enhance clarity and facilitate the identification of differences?

**Comment by lunaroja** [comment]
Great to hear! Yes, we have gotten similar feedback internally and will consider adding this in the future.
1. Currently there is not quick way to "diff" any two text documents with what we have published here. Internally, we markdown files the generate HTML files published, so we can quickly diff between any two levels, so we should make that functionality more accessible externally.
2. We can also consider adding more detailed summaries to each level and aggregating them via table for quick reference.

**Comment by Alexxtheonly** [comment]
We used chatGPT to summarize it into a table like this:

![image](https://github.com/dropbox/dbx-career-framework/assets/5155072/45fad087-1702-4e6f-8d06-357366b35925)

I will close this issue because our question is answered :) tank you @lunaroja

**Comment by lunaroja** [comment]
Such a great idea, @Alexxtheonly !
